language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: clang
      addons: &clang38
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.8', 'libclang-3.8-dev']
      env: COMPILER='clang++-3.8'
    
    - os: linux
      compiler: clang
      addons: &clang39
        apt:
          sources: ['llvm-toolchain-precise-3.9', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.9', 'libclang-3.9-dev']
      env: COMPILER='clang++-3.9'
    
    - os: linux
      compiler: clang
      addons: &clang38
        apt:
          sources: ['llvm-toolchain-precise-4.0', 'ubuntu-toolchain-r-test']
          packages: ['clang-4.0', 'libclang-4.0-dev']
      env: COMPILER='clang++-4.0'

install:
  - pip install --user clang nose

before_script: 
  - export CXX=${COMPILER}
  - export LD_LIBRARY_PATH=$(dirname $(find /usr/lib/llvm-3.8 -name libclang.so))

script: ${TRAVIS_BUILD_DIR}/run_tests.sh
