sudo: required
language: python
python:
  - "2.7"

# command to install dependencies
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - curl http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libclang-3.6-dev
  - export LD_LIBRARY_PATH=$(dirname $(find /usr/lib -name libclang.so))

# install requirements and package to test
install: 
  - pip install -r requirements.txt
  - pip install -e .
  
# command to run tests
script: ./run_tests.sh
  
notifications:
    slack: c-api:Lvo4ZEfFhJVU3s0f3QtdRMXO

